# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"\\\n\nJointState\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\x12\x0f\n\x07\x65\x66\x66orts\x18\x03 \x03(\x01\x12\x16\n\x0egripper_closed\x18\x04 \x01(\x08\"N\n\x07TcpPose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02rx\x18\x04 \x01(\x01\x12\n\n\x02ry\x18\x05 \x01(\x01\x12\n\n\x02rz\x18\x06 \x01(\x01\"\x88\x01\n\nRobotState\x12!\n\x06joints\x18\x01 \x01(\x0b\x32\x11.robot.JointState\x12\x1b\n\x03tcp\x18\x02 \x01(\x0b\x32\x0e.robot.TcpPose\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x63ycle_count\x18\x04 \x01(\x05\x12\x15\n\rcurrent_skill\x18\x05 \x01(\t\"Z\n\x05\x46\x61ult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bjoint_index\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\"\x0e\n\x0c\x46\x61ultCleared\"\x8b\x01\n\rServerMessage\x12\"\n\x05state\x18\x01 \x01(\x0b\x32\x11.robot.RobotStateH\x00\x12\x1d\n\x05\x66\x61ult\x18\x02 \x01(\x0b\x32\x0c.robot.FaultH\x00\x12,\n\rfault_cleared\x18\x03 \x01(\x0b\x32\x13.robot.FaultClearedH\x00\x42\t\n\x07payload\" \n\x0cSkillCommand\x12\x10\n\x08skill_id\x18\x01 \x01(\t\"\x07\n\x05\x45Stop\"\x07\n\x05Reset\"\x7f\n\rClientMessage\x12$\n\x05skill\x18\x01 \x01(\x0b\x32\x13.robot.SkillCommandH\x00\x12\x1e\n\x06\x65_stop\x18\x02 \x01(\x0b\x32\x0c.robot.EStopH\x00\x12\x1d\n\x05reset\x18\x03 \x01(\x0b\x32\x0c.robot.ResetH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTSTATE']._serialized_start=22
  _globals['_JOINTSTATE']._serialized_end=114
  _globals['_TCPPOSE']._serialized_start=116
  _globals['_TCPPOSE']._serialized_end=194
  _globals['_ROBOTSTATE']._serialized_start=197
  _globals['_ROBOTSTATE']._serialized_end=333
  _globals['_FAULT']._serialized_start=335
  _globals['_FAULT']._serialized_end=425
  _globals['_FAULTCLEARED']._serialized_start=427
  _globals['_FAULTCLEARED']._serialized_end=441
  _globals['_SERVERMESSAGE']._serialized_start=444
  _globals['_SERVERMESSAGE']._serialized_end=583
  _globals['_SKILLCOMMAND']._serialized_start=585
  _globals['_SKILLCOMMAND']._serialized_end=617
  _globals['_ESTOP']._serialized_start=619
  _globals['_ESTOP']._serialized_end=626
  _globals['_RESET']._serialized_start=628
  _globals['_RESET']._serialized_end=635
  _globals['_CLIENTMESSAGE']._serialized_start=637
  _globals['_CLIENTMESSAGE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
